# Generated by Django 4.0 on 2022-03-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social_media_links',
        ),
    ]
